[tool.poetry]
name = "innverse-stats"
version = "0.1.0"
description = "Django backend for innverse-stats app"
authors = ["Cameron Blankenbuehler <cameron.blankenbuehler@protonmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "innverse"}]

[tool.poetry.dependencies]
python = ">= 3.10, < 3.12"
beautifulsoup4 = "^4.12.2"
certifi = "2023.07.22"
charset-normalizer = "^3.2.0"
idna = "^3.4"
requests = "^2.28.2"
soupsieve = "^2.4.1"
urllib3 = "^1.26.18"
djangorestframework = "^3.14.0"
stem = "^1.8.1"
pysocks = "^1.7.1"
fake-useragent = "^1.1.3"
plotly = "^5.14.1"
pandas = "^2.0.3"
django-tailwind = "^3.5.0"
pygobject = "^3.44.1"
django-browser-reload = "^1.11.0"
django = "^4.1.10"
scipy = "1.10.0"
django-debug-toolbar = "^4.2.0"
django-tables2 = "^2.6.0"
psycopg2 = "^2.9.9"
pandas-stubs = "^2.1.4.231218"
tablib = "^3.5.0"
regex = "^2023.12.25"
python-dotenv = "^1.0.0"
uvicorn = "^0.26.0"
gunicorn = "^21.2.0"
pymemcache = "^4.0.0"
kaleido = "0.2.1"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.3"
pylint-django = "^2.5.3"
ipython = "^8.14.0"
django-pattern-library = "^1.0.0"
statsmodels = "^0.14.0"
pre-commit = "^3.3.3"
pylsp-mypy = "^0.6.8"
django-stubs = {extras = ["compatible-mypy"], version = "^4.2.7"}
mypy = "^1.7.1"
pyflame = "^0.3.1"
django-debug-toolbar-template-profiler = "^2.1.0"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "innverse.settings"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
