[tool.poetry]
name = "innverse-stats"
version = "0.1.0"
description = "Django backend for innverse-stats app"
authors = ["Cameron Blankenbuehler <cameron.blankenbuehler@protonmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "innverse_stats"}]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.2"
certifi = "^2022.12.7"
charset-normalizer = "^3.1.0"
idna = "^3.4"
requests = "^2.28.2"
soupsieve = "^2.4.1"
urllib3 = "^1.26.15"
django = "^4.2"
djangorestframework = "^3.14.0"
psycopg = "^3.1.8"


[tool.poetry.group.dev.dependencies]
pylint = "^2.17.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
