# Generated by Django 4.2 on 2023-05-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(default='', unique=True)),
                ('is_interlude', models.BooleanField()),
                ('source_url', models.URLField(unique=True)),
                ('post_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.book')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rgb', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TextRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('line_number', models.PositiveIntegerField()),
                ('start_column', models.PositiveIntegerField()),
                ('end_column', models.PositiveIntegerField()),
                ('context_offset', models.PositiveBigIntegerField(default=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='LevelingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('faith_based', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CL', 'Class'), ('SK', 'Skill'), ('SP', 'Spell'), ('MR', 'Miracle')], max_length=2)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.color')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.volume'),
        ),
    ]
