# Generated by Django 4.2 on 2023-05-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField(default='')),
            ],
            options={
                'ordering': ['volume', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('is_interlude', models.BooleanField()),
                ('source_url', models.URLField()),
                ('post_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('download_date', models.DateTimeField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.book')),
            ],
            options={
                'ordering': ['book', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Color Categories',
            },
        ),
        migrations.CreateModel(
            name='RefType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('CL', 'Class'), ('CO', 'Class Obtained'), ('SK', 'Skill'), ('SO', 'Skill Obtained'), ('SP', 'Spell'), ('SB', 'Spell Obtained'), ('CH', 'Character'), ('IT', 'Item'), ('LO', 'Location')], max_length=2, null=True)),
                ('description', models.CharField(default='', max_length=120)),
                ('is_divine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Ref Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField(default='')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TextRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('line_number', models.PositiveIntegerField()),
                ('start_column', models.PositiveIntegerField()),
                ('end_column', models.PositiveIntegerField()),
                ('context_offset', models.PositiveBigIntegerField(default=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.chapter')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.reftype')),
            ],
            options={
                'verbose_name_plural': 'Text Refs',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.colorcategory')),
            ],
            options={
                'ordering': ['rgb'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.volume'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('ref_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.reftype')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
    ]
