# Generated by Django 4.2 on 2023-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelingTokens',
            new_name='LevelingToken',
        ),
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(default='', unique=True),
        ),
    ]
