# Generated by Django 4.1.10 on 2023-10-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0015_alter_chapter_word_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Chapter Lines",
                "ordering": ["chapter", "line_number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="textref",
            name="key",
        ),
        migrations.RemoveField(
            model_name="textref",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="textref",
            name="context_offset",
        ),
        migrations.RemoveField(
            model_name="textref",
            name="line_number",
        ),
        migrations.RemoveField(
            model_name="textref",
            name="text",
        ),
        migrations.AddConstraint(
            model_name="textref",
            constraint=models.UniqueConstraint(
                fields=("type", "start_column", "end_column"), name="key"
            ),
        ),
        migrations.AddField(
            model_name="chapterline",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.chapter"
            ),
        ),
        migrations.AddField(
            model_name="textref",
            name="chapter_line",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.chapterline",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="chapterline",
            constraint=models.UniqueConstraint(
                fields=("chapter", "line_number"), name="unique_chapter_and_line"
            ),
        ),
    ]
