# Generated by Django 4.1.10 on 2023-10-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0016_chapterline_remove_textref_key_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="textref",
            name="key",
        ),
        migrations.AddConstraint(
            model_name="textref",
            constraint=models.UniqueConstraint(
                fields=("chapter_line", "start_column", "end_column"), name="key"
            ),
        ),
    ]
