# Generated by Django 4.1.12 on 2023-10-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0017_remove_textref_key_textref_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="textref",
            options={
                "ordering": ["chapter_line__chapter"],
                "verbose_name_plural": "Text Refs",
            },
        ),
        migrations.RenameField(
            model_name="character",
            old_name="first_chapter_ref",
            new_name="first_chapter_appearance",
        ),
        migrations.AlterField(
            model_name="book",
            name="number",
            field=models.PositiveBigIntegerField(verbose_name="Book Number"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Book Title"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Chapter Title"),
        ),
        migrations.AlterField(
            model_name="color",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.colorcategory",
                verbose_name="Color Category",
            ),
        ),
        migrations.AlterField(
            model_name="colorcategory",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="volume",
            name="number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Volume Number"
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="title",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Volume Title"
            ),
        ),
    ]
