# Generated by Django 4.2.8 on 2024-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0021_remove_reftype_is_divine_alter_reftype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reftype",
            name="type",
            field=models.CharField(
                choices=[
                    ("CH", "Character"),
                    ("CL", "Class"),
                    ("CO", "Class Obtained"),
                    ("IT", "Item"),
                    ("LO", "Location"),
                    ("MI", "Miracle"),
                    ("SK", "Skill"),
                    ("SO", "Skill Obtained"),
                    ("SP", "Spell"),
                    ("SB", "Spell Obtained"),
                    ("IN", "Invalid category"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
