# Generated by Django 4.2.8 on 2024-01-10 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0022_alter_reftype_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textref",
            options={
                "ordering": [
                    "chapter_line__chapter",
                    "chapter_line__line_number",
                    "start_column",
                ],
                "verbose_name_plural": "Text Refs",
            },
        ),
    ]
