# Generated by Django 4.2.8 on 2024-01-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0023_alter_textref_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reftype",
            name="type",
            field=models.CharField(
                choices=[
                    ("CH", "Character"),
                    ("CL", "Class"),
                    ("CO", "Class Updated"),
                    ("IT", "Item"),
                    ("LO", "Location"),
                    ("MI", "Miracle"),
                    ("SK", "Skill"),
                    ("SO", "Skill Updated"),
                    ("SP", "Spell"),
                    ("SB", "Spell Updated"),
                    ("IN", "Undecided"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
