# Generated by Django 4.2.8 on 2024-01-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0025_alter_reftype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reftype",
            name="type",
            field=models.CharField(
                choices=[
                    ("CH", "Character"),
                    ("CL", "Class"),
                    ("CU", "Class Update"),
                    ("IT", "Item"),
                    ("LO", "Location"),
                    ("MI", "Miracle"),
                    ("SK", "Skill"),
                    ("SU", "Skill Update"),
                    ("SP", "Spell"),
                    ("PU", "Spell Update"),
                    ("UN", "Undecided"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
