# Generated by Django 4.2.8 on 2024-01-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0030_alter_reftype_name_alter_reftype_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefTypeChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "RefType Chapters",
            },
        ),
        migrations.RemoveConstraint(
            model_name="textref",
            name="key",
        ),
        migrations.AddConstraint(
            model_name="textref",
            constraint=models.UniqueConstraint(
                fields=("chapter_line", "start_column", "end_column"),
                name="textref_key",
            ),
        ),
        migrations.AddField(
            model_name="reftypechapters",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.chapter"
            ),
        ),
        migrations.AddField(
            model_name="reftypechapters",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.reftype"
            ),
        ),
        migrations.AddConstraint(
            model_name="reftypechapters",
            constraint=models.UniqueConstraint(
                fields=("type", "chapter"), name="reftype_chapters_key"
            ),
        ),
    ]
