# Generated by Django 4.2.8 on 2024-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0033_reftype_stats_refty_id_ecda81_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="is_canon",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_status_update",
            field=models.BooleanField(default=False),
        ),
    ]
