# Generated by Django 5.0.2 on 2024-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0035_reftype_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reftype",
            name="description",
        ),
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(verbose_name="Book Title"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.TextField(verbose_name="Chapter Title"),
        ),
        migrations.AlterField(
            model_name="reftype",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="volume",
            name="title",
            field=models.TextField(unique=True, verbose_name="Volume Title"),
        ),
    ]
