# Generated by Django 5.0.2 on 2024-02-09 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0036_remove_reftype_description_alter_alias_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="rgb",
            field=models.CharField(
                max_length=6,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z\\d]{6}$")],
            ),
        ),
        migrations.AddIndex(
            model_name="textref",
            index=models.Index(fields=["type"], name="stats_textr_type_id_db4dd9_idx"),
        ),
    ]
