# Generated by Django 5.0.2 on 2024-02-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0037_alter_color_rgb_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reftype",
            name="stats_refty_id_ecda81_idx",
        ),
        migrations.AddIndex(
            model_name="reftype",
            index=models.Index(fields=["name"], name="stats_refty_name_b647fb_idx"),
        ),
        migrations.AddIndex(
            model_name="reftype",
            index=models.Index(fields=["type"], name="stats_refty_type_a08176_idx"),
        ),
    ]
