# Generated by Django 5.0.2 on 2024-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0038_remove_reftype_stats_refty_id_ecda81_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["number"], name="stats_chapt_number_aff693_idx"),
        ),
    ]
