# Generated by Django 5.0.2 on 2024-02-09 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0039_chapter_stats_chapt_number_aff693_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="textref",
            name="stats_textr_type_id_db4dd9_idx",
        ),
    ]
