# Generated by Django 5.0.2 on 2024-02-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0041_alter_character_species"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="id",
        ),
        migrations.AlterField(
            model_name="character",
            name="ref_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="stats.reftype",
            ),
        ),
    ]
