# Generated by Django 5.0.2 on 2024-02-15 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0042_remove_character_id_alter_character_ref_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="ref_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="stats.reftype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ref_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="stats.reftype"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="ref_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="stats.reftype"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="ref_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="stats.reftype"
            ),
        ),
        migrations.AlterField(
            model_name="spell",
            name="ref_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="stats.reftype"
            ),
        ),
        migrations.AddConstraint(
            model_name="alias",
            constraint=models.UniqueConstraint(
                fields=("name", "ref_type"), name="unique_alias"
            ),
        ),
    ]
