# Generated by Django 5.0.2 on 2024-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0043_alter_character_ref_type_alter_item_ref_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="number",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.TextField(unique=True, verbose_name="Chapter Title"),
        ),
    ]
