# Generated by Django 5.0.7 on 2024-10-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0045_reftypecomputedview_reftype_letter_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.TextField(),
        ),
    ]
