# Generated by Django 5.0.7 on 2024-10-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0046_alter_alias_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("volume", "number"), name="unique_volume_and_book_num"
            ),
        ),
    ]
