# Generated by Django 5.0.9 on 2024-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0047_book_unique_volume_and_book_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title_short",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.Func(
                        models.F("title"),
                        models.Value("(\\w+\\s\\w+)\\s"),
                        function="regexp_substr",
                    ),
                    function="trim",
                ),
                output_field=models.TextField(),
            ),
        ),
    ]
