# Generated by Django 5.0.9 on 2024-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0048_book_title_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="title_short",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.F("title"),
                    models.Value("^Interlude"),
                    models.Value("I."),
                    function="regexp_replace",
                ),
                output_field=models.TextField(),
            ),
        ),
    ]
