# Generated by Django 5.2.3 on 2025-09-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0050_alter_character_species_alter_character_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="digest",
            field=models.CharField(default=""),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("digest__length", 64), ("digest__length", 0), _connector="OR"
                ),
                name="digest_length",
            ),
        ),
    ]
