# Generated by Django 5.2.3 on 2025-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0052_alter_character_species_alter_reftype_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reftype",
            constraint=models.UniqueConstraint(
                fields=("slug", "type"), name="unique_slug_and_type"
            ),
        ),
    ]
