# Generated by Django 5.2.3 on 2025-10-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0053_reftype_unique_slug_and_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="title_short",
        ),
    ]
