# Generated by Django 5.2.7 on 2025-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0054_remove_book_title_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterline",
            name="text_plain",
            field=models.TextField(default=""),
        ),
    ]
