# Generated by Django 5.2.7 on 2025-10-10 23:05

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0055_chapterline_text_plain"),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGinExtension(),
        migrations.AddIndex(
            model_name="chapterline",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "text_plain", config="english"
                ),
                name="chapterline_search_vector_idx",
            ),
        ),
    ]
