# Generated by Django 5.2.7 on 2025-10-12 23:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0056_create_extension_btree_gin_and_more_updated"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chapterline",
            new_name="search_vector_idx",
            old_name="chapterline_search_vector_idx",
        ),
        migrations.AddIndex(
            model_name="chapterline",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "text_plain", config="english_nostop"
                ),
                name="search_vector_no_stop_idx",
            ),
        ),
    ]
