# Generated by Django 5.2.7 on 2025-10-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0057_rename_chapterline_search_vector_idx_search_vector_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="authors_note_word_count",
        ),
        migrations.AddField(
            model_name="chapter",
            name="authors_note",
            field=models.TextField(default=""),
        ),
    ]
