# Generated by Django 5.2.7 on 2025-10-27 00:36

import stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0058_remove_chapter_authors_note_word_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="authors_note_word_count",
            field=models.GeneratedField(
                db_persist=True,
                expression=stats.models.WordCount(models.F("authors_note")),
                output_field=models.PositiveIntegerField(default=0),
            ),
        ),
    ]
