name: Innverse Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install build deps
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev # deps for pycairo
          sudo apt-get install -y libgirepository-2.0-dev # deps for pygobject
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          TWI_KEY: ${{ secrets.TWI_KEY }}
          PYWIKIBOT_DIR: ${{ secrets.PYWIKIBOT_DIR }}
          PYWIKIBOT_USER: ${{ secrets.PYWIKIBOT_USER }}
          PYWIKIBOT_BOT_NAME : ${{ secrets.PYWIKIBOT_BOT_NAME }}
          PYWIKIBOT_PASS: ${{ secrets.PYWIKIBOT_PASS }}
        run: uv run pytest
